---
- name: Install i3wm
  pacman:
    name:
      - dmenu
      - i3lock
      - i3status
      - picom-tryone-git
      - i3-gaps
    state: present
    update_cache: yes
  become: true

- include_role:
    name: xorg

- include_role:
    name: sxhkd
