---
- name: Install libvirt requirements
  become: true
  pacman:
    name:
      - python-lxml

- name: install libvirt and QEMU
  become: true
  pacman:
    name:
      # - dmidecode
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager
    state: present

- name: enable libvirtd
  systemd:
    name: libvirtd.service
    state: started
    enabled: true
  become: true

- name: add user to libvirt group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups:
      - libvirt
    append: true

- community.libvirt.virt_net:
    autostart: yes
    name: default
