---
- name: Create user aur_builder
  become: true
  user:
    name: aur_builder
    group: wheel
- name: give aur_builder sudo access
  become: true
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    validate: visudo -cf %s

- name: Install apps
  become: true
  become_user: aur_builder
  aur:
    name:
      - cronie
      - yadm
    state: present

- name: Make sure cronie service unit is running
  become: true
  ansible.builtin.systemd:
    state: started
    name: cronie

- name: Cron to keep dotfiles in sync
  become_user: "{{ lookup('env','USR') }}"
  cron:
    name: "Keep yadm in sync"
    minute: "*/10"
    job: "yadm pull"
  notify: restart cron
  tags: cron
