---
#- hosts: 127.0.0.1
- hosts: vm
  #connection: local
  tasks:
    #- name: Ensure ansible user accepts the SSH key
      #authorized_key:
        #user: '{{ ansible_user }}'
        #key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
        #state: present

    - name: Disable root login
      become: true
      user:
        name: root
        password: '!'

    - name: Configure Grub
      become: true
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        line: '{{ item }}'
      with_items:
        - 'GRUB_DEFAULT=saved'
        - 'GRUB_SAVEDEFAULT=true'


  roles:
    - kewlfft.aur
    - paru
    - cpu
    - zsh
    - yadm
    - xorg
    - dwm
    - apps
    #- bspwm
    #- firefox
    #- i3wm
    #- laptop
    #- libvirtd
    #- nvidia
    #- sway
    #- vscodium_extensions
