---
- hosts: 127.0.0.1
  # - hosts: vm
  connection: local
  roles:
    - kewlfft.aur
    - apps
    - bspwm
    - cpu
    - firefox
    - i3wm
    - laptop
    - libvirtd
    - nvidia
    - paru
    - sway
    - vscodium_extensions
    - zsh
