---
- hosts: 127.0.0.1
    #- hosts: vm
  connection: local
  roles:
    - yay
    - sway
    - zsh
    # - i3wm
    # - bspwm
    # - nvidia
    - apps
    # - vscodium_extensions
    # - firefox
    # - laptop
