---
- hosts: 127.0.0.1
  connection: local
  roles:
    - kewlfft.aur
    - yay
    - sway
    - gui_tty1
    #- i3wm
    #- bspwm
    #- nvidia
    - apps
    #- vscodium_extensions
    #- firefox
    #- laptop
