---
- name: Install bspwm
  become: true
  become_user: aur_builder
  aur:
    name:
      - bspwm
      - dmenu
      - picom-tryone-git
    state: present

- include_role:
    name: xorg

- include_role:
    name: sxhkd
