---
    - name: Remove old .mozilla
      shell: rm -rfv "$HOME/.mozilla"
    - name: Create "{{ lookup('env', 'USER') }}" profile
      shell: firefox --CreateProfile "$USER $HOME/.config/mozilla/firefox/$USER"

    - name: customize firefox
      lineinfile:
          path: "{{ lookup('env','HOME') }}/.config/mozilla/firefox/{{ lookup('env', 'USER') }}/prefs.js"
          regexp: '{{ item.regexp }}'
          line: '{{ item.line }}'
          state: present
      with_items:
    # Compact UI
          - {regexp: ^user_pref\("browser.uidensity.*, line: 'user_pref("browser.uidensity", 4);'}
    # Warm on close off
          - {regexp: ^user_pref\("browser.tabs.warnOnClose.*, line: 'user_pref("browser.tabs.warnOnClose", false);'}
    # CSS customizations
          - {regexp: ^user_pref\("toolkit.legacyUserProfileCustomizations.stylesheets.*, line: 'user_pref("toolkit.legacyUserProfileCustomizations.stylesheets",
                true);'}
    # Search Engine
          - {regexp: ^user_pref\("browser.urlbar.placeholderName.*, line: 'user_pref("browser.urlbar.placeholderName", "DuckDuckGo");'}
    # Privacy
          - {regexp: ^user_pref\("privacy.donottrackheader.ena.*, line: 'user_pref("privacy.donottrackheader.enabled", true);'}
    # Theme
          - {regexp: ^user_pref\("extensions.activeThemeID.*, line: 'user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");'}
    # Theme
          - {regexp: ^user_pref\("signon.rememberSignons.*, line: 'user_pref("signon.rememberSignons", false);'}
