---
- name: Configure tty1 to autostart X or Wayland
  become: true
  copy: 
    dest: "/etc/zsh/zshenv"
    content: |
      export XDG_CONFIG_HOME="$HOME/.config"
      export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

      # Start graphical server on tty1 if not already running.
      command -v sway >/dev/null && [ "$(tty)" = "/dev/tty1" ] && [ -z $DISPLAY ] && exec sway 
      [ "$(tty)" = "/dev/tty1" ] && ! pgrep -x Xorg >/dev/null && exec startx
