---
- name: Check for dependencies
  become: yes
  pacman:
    name:
      - base-devel
      - go
      - git
    state: present

- name: Check for yay
  become: yes
  pacman:
    name:
      - yay
  ignore_errors: yes
  register: yay


- debug:
    var: yay

- name: Clone Yay repository
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ ansible_env.HOME }}/yay"
    version: "master"
  when: '"already installed" not in yay.msg'

- name: MAKEPKG yay AUR helper
  shell: "makepkg -f --clean" 
  args:
    chdir: "{{ ansible_env.HOME }}/yay"
  when: '"already installed" not in yay.msg'

- name: Install yay
  shell: "pacman -U --noconfirm {{ ansible_env.HOME }}/yay/yay*zst"
  become: true
  when: '"already installed" not in yay.msg'

- name: Remove yay dir
  file:
    path: "{{ ansible_env.HOME }}/yay"
    state: absent
